san-cli@next
ecomfe/san-cli pull request #186
Opened 2021-01-22 08:00 UTC by jinzhan

2021-01-22 09:40 UTC, ksky521 requested changes

2021-01-22 11:48 UTC, jinzhan commented on packages/san-cli-plugin-dashboard/package.json
> +        "webpack": "~5.13.0"
好的

2021-01-26 08:23 UTC, Lohoyo commented on packages/san-cli-webpack/serve.js
> -        webpackConfig.plugins.push(new NameModulesPlugin());
这一行删了，是不是要加多一行：

`webpackConfig.optimization.moduleIds = 'named';`

参考：https://webpack.js.org/migrate/5/#update-outdated-options
（打开链接后搜索 NamedModulesPlugin）

2021-01-26 08:29 UTC, Lohoyo commented on packages/san-cli-service/configs/base.js
> -                    .use(require('webpack/lib/NamedModulesPlugin'))
既然这一行删了，那是不是要加多一行：

`webpackConfig.optimization.moduleIds = 'named';`

参考：https://webpack.js.org/migrate/5/#update-outdated-options
（打开链接后搜索 NamedModulesPlugin）

2021-01-27 13:12 UTC, merged