解决 san-loader 的 ES6 的问题
ecomfe/san-cli pull request #56
Opened 2020-08-26 16:36 UTC by Lohoyo

2020-08-26 16:40 UTC, Lohoyo commented on packages/san-loader/lib/blocks/script.js
> -    export * from '${resource}';
`export * from '${resource}';`
这行代码我判断是没用的，所以删了。请重点关注下，防止我判断出错。

2020-08-27 05:45 UTC, ksky521 requested changes
1. 依赖没区分好开发依赖和项目依赖
2. `export *` 保留
3. object-assign 去掉，runtime的自己写个循环把功能实现
4. 测试用例补全引入`esModule`的case

2020-08-27 08:18 UTC, Lohoyo commented
> 2. `export *` 保留

这个好像没法保留，因为原来是 export * 和 export default 同时存在（如下图所示），现在 export default 改成了 module.exports =，那 export * 怎么改好像都有问题。
![image](https://user-images.githubusercontent.com/28821810/91415594-dc6fe500-e880-11ea-8b86-a31aa7276009.png)

2020-09-01 07:47 UTC, ksky521 requested changes
解决es5中export default 和 export * 的问题

2020-09-09 08:40 UTC, ksky521 requested changes

2020-09-09 08:40 UTC, ksky521 commented on packages/san-loader/lib/blocks/script.js
> +        ${options.esModule ? `import script from '${resource}';` : `var script = require('${resource}').default;`}
这里是不是需要判断下require进来的文件，是不是ES6的，不是ES6 就没有 default，判断方法是`__esModule`

2020-09-10 08:06 UTC, merged