san cli ui
ecomfe/san-cli pull request #57
Opened 2020-09-01 03:08 UTC by jinzhan

2020-09-01 03:17 UTC, ksky521 commented on packages/san-cli-command-init/index.js
> +        default: '',
这里添加hidden，不是常用的，只是内部用

2020-09-01 03:18 UTC, ksky521 commented on packages/san-cli-command-init/tasks/generator.js
> +        const projectPresets = options.projectPresets && JSON.parse(options.projectPresets);
json parse加个try cache

2020-09-01 03:21 UTC, ksky521 commented on packages/san-cli-command-init/utils/promptsValidator.js
> +};
换行

2020-09-01 03:26 UTC, ksky521 commented on packages/san-cli-ui-addon-tasks/.browserslistrc
> +iOS >= 9
这里不用ios和Android了吧，直接只考虑chrome和firefox就够了

2020-09-01 03:27 UTC, ksky521 commented on packages/san-cli-ui-addon-tasks/.editorconfig
> +semi = true
换行

2020-09-01 03:27 UTC, ksky521 commented on packages/san-cli-ui-addon-tasks/.fecsrc
> +}
换行

2020-09-01 03:28 UTC, ksky521 commented on packages/san-cli-ui-addon-tasks/package.json
> +    "eslint": "^6.8.0",
为什么给他单独做个eslint和lint-staged？

2020-09-01 03:30 UTC, ksky521 commented on packages/san-cli-ui-addon-tasks/src/utils/assets.js
> +                big: size > 250000,
250000改成变量声明放到头部

2020-09-01 03:31 UTC, ksky521 commented on packages/san-cli-ui-addon-widgets/.browserslistrc
> +iOS >= 9
同上，chrome+Firefox，不会移动下用

2020-09-01 03:31 UTC, ksky521 commented on packages/san-cli-ui-addon-widgets/.editorconfig
> +semi = true
换行

2020-09-01 03:33 UTC, ksky521 commented on packages/san-cli-ui/.browserslistrc
> +not dead
chrome+Firefox

2020-09-01 03:35 UTC, ksky521 commented on packages/san-cli-ui/client/components/connection-status/connection-status.less
> +}
换行

2020-09-01 04:57 UTC, ksky521 commented on packages/san-cli-ui/package.json
> +        "santd": "^0.3.0",
把santd、san、san-router之类的版本号，都跟其他的包都对齐

2020-09-01 04:59 UTC, ksky521 commented on packages/san-cli-ui/plugins/task.js
> +                const statsFile = path.resolve(api.getCwd(), `./node_modules/.stats-${type}.json`);
这里的路径跟lib里面的都是拼的，最好是拿到同一个地方去维护

2020-09-01 05:00 UTC, ksky521 commented on packages/san-cli-ui/plugins/task.js
> +        icon: require('./utils/getImageUrl')('/public/san.svg'),
getImageUrl不要引入两次了，拿到上面去？

2020-09-01 05:02 UTC, ksky521 commented on packages/san-cli-ui/server/connectors/logs.js
> +const shortId = require('shortid');
我记得哪个包用了nanoid，所以两个统一下

2020-09-01 05:13 UTC, ksky521 commented on packages/san-cli-ui/server/connectors/widgets.js
> +const shortid = require('shortid');
shortid 和 nanoid选一个

2020-09-01 05:22 UTC, ksky521 commented on packages/san-cli-ui/commander.js
> +            if (process.env.SAN_CLI_UI_DEV !== 'true') {
这里还是用textColor吗？

2020-09-01 05:23 UTC, ksky521 commented on packages/san-cli-ui/plugins/widgets.js
> +
注释干掉？

2020-09-01 05:25 UTC, ksky521 commented on packages/san-cli-ui/server/api/PluginManager.js
> +            namespace = '';
要不要加个cache，每次都new？

2020-09-01 05:26 UTC, ksky521 requested changes
看下评论吧

2020-09-01 05:52 UTC, harttle commented on packages/san-cli-command-init/tasks/generator.js
> +        if (projectPresets) {
这个函数好大啊，能否切分下功能，比如新增的这块逻辑就可以搞到新的函数里

2020-09-01 05:52 UTC, harttle commented on packages/san-cli-command-init/utils/promptsValidator.js
> +/**
这个文件名和其他好像不一样？比如目录 san-cli-command-init 是 snake case，这个文件是 camel case。要不要考虑项目内统一文件命名风格

2020-09-01 05:52 UTC, harttle commented on packages/san-cli-plugin-dashboard/lib/DashboardPlugin.js
> +function getTimeMessage(timer) {
timer 参数看起来是一个时间点，不是定时器。为啥命名成定时器

2020-09-01 05:52 UTC, harttle commented on packages/san-cli-ui-addon-widgets/.fecsrc
> +}
换行？EOL、EOF 可以加到 editorconfig 里吧

2020-09-01 05:52 UTC, harttle commented on packages/san-cli-ui-addon-widgets/src/components/run-task/run-task.js
> +        const task = await this.$apollo.query({
这个 init 是异步的，期间如果发生操作会不会有问题，确认下。比如先跑了 runTask，后 init 的情况。

2020-09-01 06:03 UTC, Justineo commented on packages/san-cli-command-init/utils/promptsValidator.js
> +/**
https://github.com/loeffel-io/ls-lint

是不是可以加个这个

2020-09-04 06:51 UTC, jinzhan commented on packages/san-cli-ui-addon-tasks/package.json
> +    "eslint": "^6.8.0",
这个之前是san-cli创建时自动生成的，已处理

2020-09-04 06:52 UTC, jinzhan commented on packages/san-cli-ui-addon-tasks/src/utils/assets.js
> +                big: size > 250000,
done

2020-09-04 07:04 UTC, jinzhan commented on packages/san-cli-ui-addon-widgets/.browserslistrc
> +iOS >= 9
done

2020-09-04 07:42 UTC, jinzhan commented on packages/san-cli-ui/plugins/task.js
> +        icon: require('./utils/getImageUrl')('/public/san.svg'),
嗯，这个是准备干掉的

2020-09-04 07:43 UTC, jinzhan commented on packages/san-cli-ui/server/connectors/logs.js
> +const shortId = require('shortid');
没有找到有用nanoid的

2020-09-04 07:46 UTC, jinzhan commented on packages/san-cli-ui/commander.js
> +            if (process.env.SAN_CLI_UI_DEV !== 'true') {
嗯，搞个commonColor

2020-09-04 07:50 UTC, jinzhan commented on packages/san-cli-ui/plugins/widgets.js
> +
done

2020-09-04 07:53 UTC, jinzhan commented on packages/san-cli-ui/server/api/PluginManager.js
> +            namespace = '';
每个插件只会new一次，这个地方可以不用cache

2020-09-04 07:56 UTC, jinzhan commented on packages/san-cli-ui-addon-widgets/.fecsrc
> +}
嗯，这个干掉了，用公共的配置

2020-09-04 09:11 UTC, zttonly commented on packages/san-cli-ui-addon-widgets/src/components/run-task/run-task.js
> +        const task = await this.$apollo.query({
做了一下测试，没有问题，init的作用是拿到taskId对应命令的状态信息，task信息未返回时页面不会显示，另外每个命令都有一个单独的状态存储，当前任务在运行时，切换taskId后互不影响，这块行为与任务tab的表现是一致的

2020-09-04 09:13 UTC, jinzhan commented on packages/san-cli-command-init/utils/promptsValidator.js
> +/**
packages目录名是包名，所以是kebab-case？ls-lint这个先加了本次新增的代码目录san-cli-ui的检查，整体san-cli下的文件太多了，改不动

2020-09-25 02:51 UTC, merged